# Netlify Configuration for StorySign Platform
[build]
  base = "StorySign_Platform/frontend"
  command = "npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "18"
  CI = "true"
  GENERATE_SOURCEMAP = "false"
  ESLINT_NO_DEV_ERRORS = "true"
  DISABLE_ESLINT_PLUGIN = "true"
  REACT_APP_API_URL = "https://story-sign.onrender.com"
  REACT_APP_WS_URL = "wss://story-sign.onrender.com"
  REACT_APP_ENVIRONMENT = "production"
  REACT_APP_USE_PROXY = "true"

# API proxy to backend
[[redirects]]
  from = "/api/*"
  to = "https://story-sign.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/health"
  to = "https://story-sign.onrender.com/health"
  status = 200
  force = true

# SPA routing fallback (must be last)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Basic security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"