services:
  - type: web
    name: storysign-backend
    runtime: python
    region: oregon
    plan: starter
    buildCommand: "cd StorySign_Platform/backend && pip install -r requirements.txt"
    startCommand: "cd StorySign_Platform/backend && python main_api.py"
    healthCheckPath: "/health"
    envVars:
      # Database Configuration (TiDB Cloud)
      - key: DATABASE_HOST
        sync: false # Set this to your TiDB Cloud host
      - key: DATABASE_PORT
        value: "4000"
      - key: DATABASE_NAME
        value: "storysign"
      - key: DATABASE_USER
        sync: false # Set this to your TiDB username
      - key: DATABASE_PASSWORD
        sync: false # Set this to your TiDB password

      # Authentication & Security
      - key: JWT_SECRET
        sync: false
      - key: JWT_ALGORITHM
        value: "HS256"
      - key: JWT_EXPIRATION_HOURS
        value: "24"

      # External API Keys
      - key: GROQ_API_KEY
        sync: false
      - key: GROQ_BASE_URL
        value: "https://api.groq.com/openai/v1"
      - key: GROQ_MODEL_NAME
        value: "llama-3.2-11b-vision-preview"

      # Application Configuration
      - key: ENVIRONMENT
        value: "production"
      - key: DEBUG
        value: "false"
      - key: LOG_LEVEL
        value: "INFO"
      - key: PORT
        value: "8000"

      # CORS Configuration
      - key: ALLOWED_ORIGINS
        value: "https://storysign-platform.netlify.app,https://www.storysign-platform.netlify.app"

      # Redis Configuration (if using Redis for caching)
      - key: REDIS_URL
        sync: false

      # Performance Configuration
      - key: MAX_WORKERS
        value: "4"
      - key: WORKER_TIMEOUT
        value: "120"
      - key: MAX_REQUESTS_PER_WORKER
        value: "1000"

      # Feature Flags
      - key: ENABLE_MEDIAPIPE
        value: "true"
      - key: ENABLE_ANALYTICS
        value: "true"
      - key: ENABLE_MONITORING
        value: "true"

      # Vision Service Configuration
      - key: VISION_SERVICE_TYPE
        value: "groq"
      - key: VISION_SERVICE_ENABLED
        value: "true"

      # Rate Limiting Configuration
      - key: RATE_LIMIT_ENABLED
        value: "true"
      - key: DEFAULT_RATE_LIMIT_REQUESTS
        value: "100"
      - key: DEFAULT_RATE_LIMIT_WINDOW
        value: "3600"
