name: storysign-backend
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
      - fastapi==0.104.1
      - uvicorn[standard]==0.24.0
      - websockets==12.0
      - opencv-python==4.8.1.78
      - mediapipe==0.10.7
      - python-multipart==0.0.6
      - pydantic==2.5.0
      - numpy==1.24.3
      - pillow==10.1.0
      - python-json-logger==2.0.7
