# Simplified Netlify Configuration for StorySign Platform
[build]
  base = "StorySign_Platform/frontend"
  command = "npm run build"
  publish = "StorySign_Platform/frontend/build"

[build.environment]
  NODE_VERSION = "18"
  CI = "true"
  GENERATE_SOURCEMAP = "false"

# SPA routing fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Basic security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"